// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyUAAcademiaB.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyUAAcademiaB.Migrations.Postgres
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyUAAcademiaB.Models.Bills", b =>
                {
                    b.Property<string>("SessionStudy")
                        .HasColumnType("text")
                        .HasColumnName("session_study");

                    b.Property<string>("YearStudy")
                        .HasColumnType("text")
                        .HasColumnName("year_study");

                    b.Property<string>("PermanentCode")
                        .HasColumnType("text")
                        .HasColumnName("permanent_code");

                    b.Property<double?>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<double?>("AmountPaid")
                        .HasColumnType("double precision")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_issue");

                    b.Property<DateTime?>("DateOfPaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_paiement");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_line");

                    b.Property<double?>("DentalInsurance")
                        .HasColumnType("double precision")
                        .HasColumnName("dental_insurance");

                    b.Property<double?>("GeneralExpenses")
                        .HasColumnType("double precision")
                        .HasColumnName("general_expenses");

                    b.Property<double?>("InsuranceFees")
                        .HasColumnType("double precision")
                        .HasColumnName("insurance_fees");

                    b.Property<string>("ProgramTitle")
                        .HasColumnType("text")
                        .HasColumnName("program_title");

                    b.Property<double?>("RefundsAndAdjustments")
                        .HasColumnType("double precision")
                        .HasColumnName("refunds_and_adjustments");

                    b.Property<double?>("SportsAdministrationFees")
                        .HasColumnType("double precision")
                        .HasColumnName("sports_administration_fees");

                    b.HasKey("SessionStudy", "YearStudy", "PermanentCode")
                        .HasName("pk_bills");

                    b.HasIndex("PermanentCode")
                        .HasDatabaseName("ix_bills_permanent_code");

                    b.HasIndex("ProgramTitle")
                        .HasDatabaseName("ix_bills_program_title");

                    b.ToTable("bills", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Bulletins", b =>
                {
                    b.Property<string>("Sigle")
                        .HasColumnType("text")
                        .HasColumnName("sigle");

                    b.Property<string>("PermanentCode")
                        .HasColumnType("text")
                        .HasColumnName("permanent_code");

                    b.Property<double?>("Grade")
                        .HasColumnType("double precision")
                        .HasColumnName("grade");

                    b.Property<string>("Mention")
                        .HasColumnType("text")
                        .HasColumnName("mention");

                    b.HasKey("Sigle", "PermanentCode")
                        .HasName("pk_bulletins");

                    b.HasIndex("PermanentCode")
                        .HasDatabaseName("ix_bulletins_permanent_code");

                    b.ToTable("bulletins", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Classes", b =>
                {
                    b.Property<string>("ClasseName")
                        .HasColumnType("text")
                        .HasColumnName("classe_name");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("TypeOfClasse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_of_classe");

                    b.HasKey("ClasseName")
                        .HasName("pk_classes");

                    b.HasIndex("EmployeeCode")
                        .HasDatabaseName("ix_classes_employee_code");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.ClassesCourses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClasseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classe_name");

                    b.Property<string>("CourseSigle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_sigle");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_time");

                    b.Property<string>("Jours")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jours");

                    b.Property<string>("SessionCourse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_course");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_time");

                    b.Property<string>("TaughtBy")
                        .HasColumnType("text")
                        .HasColumnName("taught_by");

                    b.Property<string>("YearCourse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("year_course");

                    b.HasKey("Id")
                        .HasName("pk_classes_courses");

                    b.HasIndex("CourseSigle")
                        .HasDatabaseName("ix_classes_courses_course_sigle");

                    b.HasIndex("EmployeeCode")
                        .HasDatabaseName("ix_classes_courses_employee_code");

                    b.HasIndex("ClasseName", "StartTime", "Jours", "SessionCourse", "YearCourse")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_courses_classe_name_start_time_jours_session_course");

                    b.HasIndex("TaughtBy", "StartTime", "Jours", "SessionCourse", "YearCourse")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_courses_taught_by_start_time_jours_session_course_y");

                    b.ToTable("classes_courses", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Contracts", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("availability");

                    b.Property<string>("BaseSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_salary");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndingDate")
                        .HasColumnType("date")
                        .HasColumnName("ending_date");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("MaximumWage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("maximum_wage");

                    b.Property<int>("MinimumWage")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_wage");

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_hours");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date")
                        .HasColumnName("starting_date");

                    b.Property<string>("TypeOfEmployment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_of_employment");

                    b.Property<string>("TypeOfOffer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_of_offer");

                    b.Property<string>("WorkShift")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_shift");

                    b.HasKey("Code")
                        .HasName("pk_contracts");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Courses", b =>
                {
                    b.Property<string>("Sigle")
                        .HasColumnType("text")
                        .HasColumnName("sigle");

                    b.Property<int?>("Autumn")
                        .HasColumnType("integer")
                        .HasColumnName("autumn");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_title");

                    b.Property<int?>("Summer")
                        .HasColumnType("integer")
                        .HasColumnName("summer");

                    b.Property<int?>("Winter")
                        .HasColumnType("integer")
                        .HasColumnName("winter");

                    b.HasKey("Sigle")
                        .HasName("pk_courses");

                    b.HasIndex("EmployeeCode")
                        .HasDatabaseName("ix_courses_employee_code");

                    b.HasIndex("ProgramTitle")
                        .HasDatabaseName("ix_courses_program_title");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Employees", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date")
                        .HasColumnName("birth_day");

                    b.Property<string>("CreatedByCode")
                        .HasColumnType("text")
                        .HasColumnName("created_by_code");

                    b.Property<string>("EmpStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_status");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("IsActivated")
                        .HasColumnType("integer")
                        .HasColumnName("is_activated");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_validated");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int?>("Nas")
                        .HasColumnType("integer")
                        .HasColumnName("nas");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personal_email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfessionalEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("professional_email");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pwd");

                    b.Property<char>("Sexe")
                        .HasColumnType("character(1)")
                        .HasColumnName("sexe");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_role");

                    b.Property<string>("UserStatus")
                        .HasColumnType("text")
                        .HasColumnName("user_status");

                    b.HasKey("Code")
                        .HasName("pk_employees");

                    b.HasIndex("CreatedByCode")
                        .HasDatabaseName("ix_employees_created_by_code");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.EmployeesContracts", b =>
                {
                    b.Property<string>("EmpCode")
                        .HasColumnType("text")
                        .HasColumnName("emp_code");

                    b.Property<string>("ContractCode")
                        .HasColumnType("text")
                        .HasColumnName("contract_code");

                    b.Property<bool>("IsContractOver")
                        .HasColumnType("boolean")
                        .HasColumnName("is_contract_over");

                    b.Property<DateOnly?>("RealEndDate")
                        .HasColumnType("date")
                        .HasColumnName("real_end_date");

                    b.Property<string>("RealSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("real_salary");

                    b.Property<DateOnly>("RealStartingDate")
                        .HasColumnType("date")
                        .HasColumnName("real_starting_date");

                    b.HasKey("EmpCode", "ContractCode")
                        .HasName("pk_employees_contracts");

                    b.HasIndex("ContractCode")
                        .HasDatabaseName("ix_employees_contracts_contract_code");

                    b.HasIndex("EmpCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_contracts_emp_code")
                        .HasFilter("\"is_contract_over\" = false");

                    b.ToTable("employees_contracts", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Programs", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_name");

                    b.HasKey("Title")
                        .HasName("pk_programs");

                    b.HasIndex("EmployeeCode")
                        .HasDatabaseName("ix_programs_employee_code");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.StudentFiles", b =>
                {
                    b.Property<string>("FileCode")
                        .HasColumnType("text")
                        .HasColumnName("file_code");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_code");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("FileCode")
                        .HasName("pk_student_files");

                    b.ToTable("student_files", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("c_course_id");

                    b.Property<string>("PermanentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permanent_code");

                    b.HasKey("Id")
                        .HasName("pk_user_courses");

                    b.HasIndex("CCourseId")
                        .HasDatabaseName("ix_user_courses_c_course_id");

                    b.HasIndex("PermanentCode")
                        .HasDatabaseName("ix_user_courses_permanent_code");

                    b.ToTable("user_courses", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserProgramEnrollment", b =>
                {
                    b.Property<string>("PermanentCode")
                        .HasColumnType("text")
                        .HasColumnName("permanent_code");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("EndDateEstimate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_estimate");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_date");

                    b.Property<bool>("HasFinished")
                        .HasColumnType("boolean")
                        .HasColumnName("has_finished");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enrolled");

                    b.Property<DateTime?>("RealEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("real_end_date");

                    b.HasKey("PermanentCode", "Title")
                        .HasName("pk_user_program_enrollments");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_user_program_enrollments_title");

                    b.ToTable("user_program_enrollments", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Users", b =>
                {
                    b.Property<string>("PermanentCode")
                        .HasColumnType("text")
                        .HasColumnName("permanent_code");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date")
                        .HasColumnName("birth_day");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("IsActivated")
                        .HasColumnType("integer")
                        .HasColumnName("is_activated");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_validated");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int?>("Nas")
                        .HasColumnType("integer")
                        .HasColumnName("nas");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personal_email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfessionalEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("professional_email");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pwd");

                    b.Property<char>("Sexe")
                        .HasColumnType("character(1)")
                        .HasColumnName("sexe");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_role");

                    b.Property<string>("UserStatus")
                        .HasColumnType("text")
                        .HasColumnName("user_status");

                    b.HasKey("PermanentCode")
                        .HasName("pk_users");

                    b.HasIndex("EmployeeCode")
                        .HasDatabaseName("ix_users_employee_code");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Bills", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("Bills")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bills_users_permanent_code");

                    b.HasOne("MyUAAcademiaB.Models.Programs", "Program")
                        .WithMany("Bills")
                        .HasForeignKey("ProgramTitle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_bills_programs_program_title");

                    b.Navigation("Program");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Bulletins", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("Bulletins")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bulletins_users_permanent_code");

                    b.HasOne("MyUAAcademiaB.Models.Courses", "Course")
                        .WithMany("Bulletin")
                        .HasForeignKey("Sigle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bulletins_courses_sigle");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Classes", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Classes")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classes_employees_employee_code");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.ClassesCourses", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Classes", "Classe")
                        .WithMany("ClassesCourses")
                        .HasForeignKey("ClasseName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_courses_classes_classe_name");

                    b.HasOne("MyUAAcademiaB.Models.Courses", "Course")
                        .WithMany("ClassesCourses")
                        .HasForeignKey("CourseSigle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_courses_courses_course_sigle");

                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("ClassesCourses")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_courses_employees_employee_code");

                    b.HasOne("MyUAAcademiaB.Models.Employees", "TaughtByProfessor")
                        .WithMany("TaughtCourses")
                        .HasForeignKey("TaughtBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classes_courses_employees_taught_by");

                    b.Navigation("Classe");

                    b.Navigation("Course");

                    b.Navigation("Employee");

                    b.Navigation("TaughtByProfessor");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Courses", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Courses")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_employees_employee_code");

                    b.HasOne("MyUAAcademiaB.Models.Programs", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramTitle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_programs_program_title");

                    b.Navigation("Employee");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Employees", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "CreatedBy")
                        .WithMany("CreatedEmployees")
                        .HasForeignKey("CreatedByCode")
                        .HasConstraintName("fk_employees_employees_created_by_code");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.EmployeesContracts", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Contracts", "Contract")
                        .WithMany("EmployeesContracts")
                        .HasForeignKey("ContractCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_contracts_contracts_contract_code");

                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("EmployeesContracts")
                        .HasForeignKey("EmpCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_contracts_employees_emp_code");

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Programs", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Programs")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_employees_employee_code");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserCourse", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.ClassesCourses", "ClassesCourses")
                        .WithMany("UserCourse")
                        .HasForeignKey("CCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_courses_classes_courses_c_course_id");

                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("UserCourses")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_courses_users_permanent_code");

                    b.Navigation("ClassesCourses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserProgramEnrollment", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("UserProgramEnrollments")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_program_enrollments_users_permanent_code");

                    b.HasOne("MyUAAcademiaB.Models.Programs", "Programs")
                        .WithMany("UserProgramEnrollments")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_program_enrollments_programs_title");

                    b.Navigation("Programs");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Users", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeCode")
                        .HasConstraintName("fk_users_employees_employee_code");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Classes", b =>
                {
                    b.Navigation("ClassesCourses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.ClassesCourses", b =>
                {
                    b.Navigation("UserCourse");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Contracts", b =>
                {
                    b.Navigation("EmployeesContracts");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Courses", b =>
                {
                    b.Navigation("Bulletin");

                    b.Navigation("ClassesCourses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Employees", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ClassesCourses");

                    b.Navigation("Courses");

                    b.Navigation("CreatedEmployees");

                    b.Navigation("EmployeesContracts");

                    b.Navigation("Programs");

                    b.Navigation("TaughtCourses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Programs", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Courses");

                    b.Navigation("UserProgramEnrollments");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Users", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Bulletins");

                    b.Navigation("UserCourses");

                    b.Navigation("UserProgramEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
