server {
    listen ${PORT};

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Redirige tout vers index.html pour React Router
        try_files $uri $uri/ /index.html;
    }
}