name: Projet Build and Publish Docker Image 

on:
  push:
    branches:
      - docker-trial    #modify if you want to deploy on branch "docker-trial"

  
jobs:
    Deploy-Container-App:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Hadolint for checking the code' 
          uses: hadolint/hadolint-action@v3.1.0
          with:
              dockerfile: ./Dockerfile 
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Login to Docker Hub using Access Token'
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: 'Deploy Container App from Docker Hub'
          uses: azure/container-apps-deploy-action@v1
          with:
            containerAppName: uaacademia
            containerAppEnvironment: uaacademia-env
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: frimpongefrei/myapp:amd64  # This tells Azure where to pull the image from Docker Hub
            registryUrl: index.docker.io  # Specifies Docker Hub registry
            registryUsername: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username (if the image is private)
            registryPassword: ${{ secrets.DOCKERHUB_PASSWORD }}  # Docker Hub password (if the image is private)
            location: 'west us'
            targetPort: 8080
            azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
