name: Build .NET app

on:
  push:
    branches: []
    paths:
        - 'backend/**'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
    backend-ci:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      env: 
        ASPNETCORE_ENVIRONMENT: Testing
        FRONTEND_URL: "http://localhost:5173"
        Key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-------------------aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        Issuer: "issuer"
        Audience: "audience"
        ResetKey: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb**********************************bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
        ResetIssuer: "resetissuer"
        
      defaults:
        run:
          working-directory: ./backend/

      services:
        postgres:
          image: postgres:18
          env:
            POSTGRES_DB: myuaacademia_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 3

      steps:
        - name: Checkout code
          uses: actions/checkout@v5.0.1

        - name: Setup dotnet
          uses: actions/setup-dotnet@v5.2.0
          with:
            dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Check formatting
          run: dotnet format --verify-no-changes

        - name: Build
          run: dotnet build --no-restore --configuration Release

        - name: Run tests
          run: dotnet test --no-build --configuration Release --logger "console;verbosity=detailed"
          env:
            ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=myuaacademia_test;Username=postgres;Password=postgres"