// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyUAAcademiaB.Data;

#nullable disable

namespace MyUAAcademiaB.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyUAAcademiaB.Models.Bills", b =>
                {
                    b.Property<string>("SessionStudy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YearStudy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PermanentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<double?>("AmountPaid")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfPaiement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DentalInsurance")
                        .HasColumnType("float");

                    b.Property<double?>("GeneralExpenses")
                        .HasColumnType("float");

                    b.Property<double?>("InsuranceFees")
                        .HasColumnType("float");

                    b.Property<string>("ProgramTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("RefundsAndAdjustments")
                        .HasColumnType("float");

                    b.Property<double?>("SportsAdministrationFees")
                        .HasColumnType("float");

                    b.HasKey("SessionStudy", "YearStudy", "PermanentCode");

                    b.HasIndex("PermanentCode");

                    b.HasIndex("ProgramTitle");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Bulletins", b =>
                {
                    b.Property<string>("Sigle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PermanentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<string>("Mention")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sigle", "PermanentCode");

                    b.HasIndex("PermanentCode");

                    b.ToTable("Bulletins");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Classes", b =>
                {
                    b.Property<string>("ClasseName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("TypeOfClasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClasseName");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.ClassesCourses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClasseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseSigle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jours")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SessionCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaughtBy")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("YearCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseSigle");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("ClasseName", "StartTime", "Jours", "SessionCourse", "YearCourse")
                        .IsUnique();

                    b.HasIndex("TaughtBy", "StartTime", "Jours", "SessionCourse", "YearCourse")
                        .IsUnique()
                        .HasFilter("[TaughtBy] IS NOT NULL");

                    b.ToTable("ClassesCourses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Contracts", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseSalary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndingDate")
                        .HasColumnType("date");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumWage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumWage")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date");

                    b.Property<string>("TypeOfEmployment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfOffer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkShift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Courses", b =>
                {
                    b.Property<string>("Sigle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Autumn")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Summer")
                        .HasColumnType("int");

                    b.Property<int?>("Winter")
                        .HasColumnType("int");

                    b.HasKey("Sigle");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("ProgramTitle");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Employees", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByCode")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("EmpStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActivated")
                        .HasColumnType("int");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nas")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("CreatedByCode");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.EmployeesContracts", b =>
                {
                    b.Property<string>("EmpCode")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("ContractCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsContractOver")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("RealEndDate")
                        .HasColumnType("date");

                    b.Property<string>("RealSalary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RealStartingDate")
                        .HasColumnType("date");

                    b.HasKey("EmpCode", "ContractCode");

                    b.HasIndex("ContractCode");

                    b.HasIndex("EmpCode")
                        .IsUnique()
                        .HasFilter("[IsContractOver] = 0");

                    b.ToTable("EmployeesContracts");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Programs", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.StudentFiles", b =>
                {
                    b.Property<string>("FileCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileCode");

                    b.ToTable("StudentFiles");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CCourseId")
                        .HasColumnType("int");

                    b.Property<string>("PermanentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CCourseId");

                    b.HasIndex("PermanentCode");

                    b.ToTable("UserCourses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserProgramEnrollment", b =>
                {
                    b.Property<string>("PermanentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDateEstimate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RealEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PermanentCode", "Title");

                    b.HasIndex("Title");

                    b.ToTable("UserProgramEnrollments");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Users", b =>
                {
                    b.Property<string>("PermanentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActivated")
                        .HasColumnType("int");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nas")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermanentCode");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Bills", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("Bills")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Programs", "Program")
                        .WithMany("Bills")
                        .HasForeignKey("ProgramTitle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Program");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Bulletins", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("Bulletins")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Courses", "Course")
                        .WithMany("Bulletin")
                        .HasForeignKey("Sigle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Classes", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Classes")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.ClassesCourses", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Classes", "Classe")
                        .WithMany("ClassesCourses")
                        .HasForeignKey("ClasseName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Courses", "Course")
                        .WithMany("ClassesCourses")
                        .HasForeignKey("CourseSigle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("ClassesCourses")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Employees", "TaughtByProfessor")
                        .WithMany("TaughtCourses")
                        .HasForeignKey("TaughtBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Classe");

                    b.Navigation("Course");

                    b.Navigation("Employee");

                    b.Navigation("TaughtByProfessor");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Courses", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Courses")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Programs", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramTitle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Employees", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "CreatedBy")
                        .WithMany("CreatedEmployees")
                        .HasForeignKey("CreatedByCode");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.EmployeesContracts", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Contracts", "Contract")
                        .WithMany("EmployeesContracts")
                        .HasForeignKey("ContractCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("EmployeesContracts")
                        .HasForeignKey("EmpCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Programs", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Programs")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserCourse", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.ClassesCourses", "ClassesCourses")
                        .WithMany("UserCourse")
                        .HasForeignKey("CCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("UserCourses")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassesCourses");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.UserProgramEnrollment", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Users", "Student")
                        .WithMany("UserProgramEnrollments")
                        .HasForeignKey("PermanentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyUAAcademiaB.Models.Programs", "Programs")
                        .WithMany("UserProgramEnrollments")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programs");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Users", b =>
                {
                    b.HasOne("MyUAAcademiaB.Models.Employees", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeCode");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Classes", b =>
                {
                    b.Navigation("ClassesCourses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.ClassesCourses", b =>
                {
                    b.Navigation("UserCourse");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Contracts", b =>
                {
                    b.Navigation("EmployeesContracts");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Courses", b =>
                {
                    b.Navigation("Bulletin");

                    b.Navigation("ClassesCourses");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Employees", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ClassesCourses");

                    b.Navigation("Courses");

                    b.Navigation("CreatedEmployees");

                    b.Navigation("EmployeesContracts");

                    b.Navigation("Programs");

                    b.Navigation("TaughtCourses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Programs", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Courses");

                    b.Navigation("UserProgramEnrollments");
                });

            modelBuilder.Entity("MyUAAcademiaB.Models.Users", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Bulletins");

                    b.Navigation("UserCourses");

                    b.Navigation("UserProgramEnrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
